apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-angular-deployment
  labels:
    app: hello-angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-angular
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-angular
    spec:
      containers:
      - name: hello-angular
        image: fantosyyy/hello-angular:v15
        imagePullPolicy: Always
        ports:
        - containerPort: 80 # Assuming the application listens on port 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
