name: Build and Push to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login using the secrets you created in GitHub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fantosyyy
          password: ${{ secrets.dockerhub }}

      # This extracts tags (like 'latest') automatically
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fantosyyy/hello-angular

      # This builds the image using your Dockerfile and pushes it
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            fantosyyy/hello-angular:main
            fantosyyy/hello-angular:v${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
